[package]
name = "contract-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
rusqlite = "0.34"
anyhow = "1.0.97"
sha2 = "0.10.8" 
hex = "0.4.3"
log = "0.4"
env_logger = "0.10"