[package]
name = "twitter_sentiment_etl"
version = "0.1.0"
edition = "2024"

[dependencies]
vader_sentiment = "0.1"
rusqlite = { version = "0.29", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
